- name: Ensure git present
  ansible.builtin.package:
    name: git
    state: present

- name: Clone app repo
  git:
    repo: "{{ app_repo_url }}"
    dest: /opt/myapp
    version: main
    force: yes

- name: Copy Dockerfile into the app directory
  template:
    src: Dockerfile.j2
    dest: /opt/myapp/Dockerfile

- name: Build Docker image from repo
  community.docker.docker_image:
    name: "{{ image_name }}"
    source: build
    build:
      path: /opt/myapp
      dockerfile: Dockerfile



- name: Run Docker container for app
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ docker_host_port }}:{{ docker_container_port }}"
